### ISSUE TITLE
X and Y offsets not mentioned

### ISSUE THREAD

**Issue by Kruze17** [kanawati975/Voron_Switchwire#1]
what are the x and y offsets for this carriage mod?

**Comment by kanawati975** [comment]
@Kruze17 You made an issue on the main Repo. So I don't know what Mod are you talking about,
If you are referring to the Volcano Toolhead, the Offset depends on your Z-Endstop/ Z-Sensor.
Otherwise please specify the Mod you're asking about.

**Comment by Kruze17** [comment]
> @Kruze17 You made an issue on the main Repo. So I don't know what Mod are you talking about,
> If you are referring to the Volcano Toolhead, the Offset depends on your Z-Endstop/ Z-Sensor.
> Otherwise please specify the Mod you're asking about.

I am referring the bl touch mod for the x carriage.

**Comment by kanawati975** [comment]
@Kruze17 AH okay. It's -24 on the Y

**Comment by Kruze17** [comment]
> @Kruze17 AH okay. It's -24 on the Y

Thank you so much. I am closing the issue.
