### ISSUE TITLE
Phaetus BMS not supported(BL Touch mod for x-carriage)

### ISSUE THREAD

**Issue by Kruze17** [kanawati975/Voron_Switchwire#2]
I am using Phaetus BMS as hotend for my switchwire. But after a little time i found out that the probe needle of the BL touch sticks out far more than the nozzle of the hotend itself, as a result the the nozzle can't reach the bed without the bl touch probe needle crashing into the bed.
![image](https://user-images.githubusercontent.com/40540237/152498731-5a8ab26e-e545-48d2-9dee-cf053a978b28.png)

**Comment by kanawati975** [comment]
The original Mod was not made for the Pheatus BMS. It was designed for the E3D Volcano (which I thought that it's the tallest). If you can provide an accurate measurements, I would customize the Mount for your HotEnd's Hight. But first, would you please confirm that the sensor is fastened correctly?

**Comment by Kruze17** [comment]
> The original Mod was not made for the Pheatus BMS. It was designed for the E3D Volcano (which I thought that it's the tallest). If you can provide an accurate measurements, I would customize the Mount for your HotEnd's Hight. But first, would you please confirm that the sensor is fastened correctly?

No issues mate. I just wanted to inform you about this. Yes, the sensor is fastened correctly. I will close this issue.

**Comment by Maccraft123** [comment]
> The original Mod was not made for the Pheatus BMS. It was designed for the E3D Volcano (which I thought that it's the tallest). If you can provide an accurate measurements, I would customize the Mount for your HotEnd's Hight. But first, would you please confirm that the sensor is fastened correctly?

Hey, I'm also having the same problem with Bltouch sitting too low, though I'm using an E3D Revo Voron. I have measured the distance between the tip of Bltouch and end of nozzle and it's around 3.6mm. Can you modify the mount with Bltouch sitting around 6-7mm higher?

I'm attaching a photo where the Bltouch carriage and stock switchwire carriage are lined up in Z, with the nozzle at 3.6mm Z height from the bed, and Bltouch tip touching the bed
![image](https://github.com/kanawati975/Voron_Switchwire/assets/47303937/6946acfd-9e03-4e74-9212-c2c4beabd789)
